services:
  bot:
    container_name: "tashkent_air_bot"
    image: "tashkent_air_bot_img"
    stop_signal: SIGINT
    build:
      context: .
    working_dir: "/usr/src/app/bot"
    volumes:
      - .:/usr/src/app/bot
    command: python3 -m bot
    restart: always
    env_file:
      - ".env"
    networks:
      - tgbots_network
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

networks:
  tgbots_network:
    external: true